In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Tensor

### Creating Tensors


In [ ]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors


In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6440, 0.9755, 0.5502, 0.6802],
        [0.0753, 0.0612, 0.6968, 0.7509],
        [0.5100, 0.0451, 0.9353, 0.6875]])

In [ ]:
#create a random tensor with similar shape to image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

#Zeros and ones

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating range of tensors and tensors like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensor like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatype


In [ ]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
print(float_32_tensor)
float_32_tensor.dtype

tensor([3., 6., 9.])


torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

## Manipulating Tensors

In [ ]:
tensor=torch.tensor([1,2,3])
tensor+10
tensor*10
tensor-10



tensor([-9, -8, -7])

# Pytorch inbuilt function


In [ ]:
torch.mul(tensor,10)
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix multiplication


In [ ]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.17 ms, sys: 31 µs, total: 1.2 ms
Wall time: 12.3 ms


tensor(14)

## Reshaping, stacking, squeezing and unsqueezing

In [ ]:
x=torch.arange(1.,13.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped=x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
z=x.view(4,3)
z,z.shape
#changing z changes x same memory

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [ ]:
z[:,0]=5
z,x

(tensor([[ 5.,  2.,  3.],
         [ 5.,  5.,  6.],
         [ 5.,  8.,  9.],
         [ 5., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]))

In [ ]:
# stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]])

In [ ]:
# torch.squeeze
x_reshaped.squeeze()
print(f"tensor: {x_reshaped}")
print(f"\nNew tensor: {x_reshaped.squeeze()}")
print(f"new shape: {x_reshaped.squeeze().shape}")

tensor: tensor([[ 5.,  2.,  3.,  5.],
        [ 5.,  6.,  5.,  8.],
        [ 9.,  5., 11., 12.]])

New tensor: tensor([[ 5.,  2.,  3.,  5.],
        [ 5.,  6.,  5.,  8.],
        [ 9.,  5., 11., 12.]])
new shape: torch.Size([3, 4])


In [ ]:
#torch.permute
x_original=torch.rand(size=(224,224,3))
x_original.shape
x_permuted=x_original.permute(2,0,1)
x_permuted.shape
print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


#Indexing(selecting data from tensors)
###Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

# Pytorch tensors and numpy
*   data in numpy want in pytorch -> torch.from_numpy(ndarray)
*   pytorch tensor -> NumPy -> torch.Tensor.numpy()
# numpy doesnot work in gpu


In [ ]:
#numpy array to tensor
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

# Random seed

In [ ]:
random_seed=42
torch.manual_seed(random_seed)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A== random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
